### ISSUE TITLE
(unknown) : Package "rice" was not found in any of class paths

### ISSUE THREAD

**Issue by rishavs** [BlackGoku36/Rice2D#4]
Hi 

I have followed the guide at https://blackgoku36.github.io/Rice2D-Docs/#/docs/getstarted till the blank window. 

Unfortunately, trying to run the code till that point throws an "(unknown) : Package "rice" was not found in any of class paths" exception. So, I am clearly missing a step somewhere.

my khafile is
```
let project = new Project('Empty');
project.addAssets('Assets/**');
project.addSources('Sources');
project.addLibrary('rice2d');
resolve(project);
```

and my Main.hx has;
```
package;
import rice2d.App;
class Main {
    public static function main() {
        new App("");// 1
    }
}
```

EDIT:
The issue is that I need to have Kha, Rice2D and Zui in my Libraries folder to be able to compile the program. The doc doesnt mentions that.

**Comment by BlackGoku36** [comment]
Hey! Are you using latest git? If so than change your khafile to:
```
let project = new Project('New Project');
project.addAssets('Assets/**');
project.addShaders('Shaders/**');
project.addSources('Sources');
project.addLibrary('rice2d');
project.addParameter('scripts'); //new
project.addParameter("--macro keep('scripts')"); //new
resolve(project);
```
See this commit https://github.com/BlackGoku36/Rice2D/commit/0157a88dd02dd1f3ce0039fcc387c65f2dc244f2, `rice` was renamed to `scripts`(folder where you put your scripts in), But you only have to add those parameters, if you are adding any script to scene or object

About zui, yeah, you didn't need to have zui. It was small import bug, fixed at https://github.com/BlackGoku36/Rice2D/commit/14951ed6a879304d20ac597c20cbcb4f54eacb11

About Kha, there is no need to have kha. If you are using Kode studio, than Kode studio have kha bundled with it, And if you are using VSCode, than you can install plugins for kha and it will automatically install kha itself and use it. If you want latest kha(Kode studio and VScode plugin have older kha version), then you can add it as submodule to your project and set kha path from preference to this submodule

Thanks!

EDIT: Updated the doc and empty project to be able to compile latest rice2d

**Comment by rishavs** [comment]
Thanks!

> and set kha path from preference to this submodule

Can you tell me how can I do this? 
I am using VS Code. I am now trying to start a clean project using just git.
Here are the steps I am trying;

1. in the root folder do `git init`
2. create the Assets and Libraries folder
3. In the Libraries folder, add the submodules for kha, rice and zui
4. Add the khafile and the Main.hx files

I am getting ` "Error: Display file was not found in class path"` error. This is believe is because I haven't set the kha path for this project. Where should I add this reference?

**Comment by BlackGoku36** [comment]
1. Install Kha extension pack plugin in VSCode
<img width="977" alt="Screen Shot 2019-12-01 at 10 43 21 AM" src="https://user-images.githubusercontent.com/36535717/69909863-aef82700-1427-11ea-84d7-ff90f30b72d7.png">

2. Go to `Settings` - `User` - `Extensions` and add set `Kha path` to path/to/your/kha (krom is optional)

<img width="1192" alt="Screen Shot 2019-12-01 at 10 44 27 AM" src="https://user-images.githubusercontent.com/36535717/69909873-c9ca9b80-1427-11ea-8e2f-1834a0e48523.png">

* Now, open VScode in empty folder and press `F1` and type `Init Kha Project`. This will create normal kha project, and try running it.
* Now, in newly create kha project, edit `khafile.js` and `Main.hx` and add rice2d, zui to `Libraries` folder

**Comment by rishavs** [comment]
Thanks.
