### ISSUE TITLE
Community?

### ISSUE THREAD

**Issue by rishavs** [BlackGoku36/Rice2D#7]
I know, early days. But congratulations on the new release. 🎉 
I was wondering if you are thinking of setting up something like a Gitter? I suppose when Rice2D gets big enough you can move to the Haxe Discord as a separate channel.

Opening a GH issue for every (non-bug) question feels iffy

**Comment by BlackGoku36** [comment]
Thanks!
I was thinking of making seperate discord server, so that we can have channels and stuffs. We can make discord bots that bridge to Haxe discord's `#general`,`#kha` channel and create irc bot to connect to kha irc

**Comment by BlackGoku36** [comment]
Here is the discord server: https://discord.gg/Tym4Gd8

**Comment by rishavs** [comment]
Nice. Would recommend adding it to the readme as a badge
